var trainerData = [
    {
        "id": 1,
        "name": "Bradman",
        "location": "Yew (Outer area)",
        "cost": 30,
        "train": 2,
        "combat": 0,
        "dexterity": 2,
        "intelligence": 0,
        "magic": 0,
        "strength": 0
    },
    {
        "id": 2,
        "name": "Chad",
        "location": "Moonglow (far South)",
        "cost": 45,
        "train": 3,
        "combat": 1,
        "dexterity": 2,
        "intelligence": 0,
        "magic": 0,
        "strength": 0
    },
    {
        "id": 3,
        "name": "De Snel",
        "location": "Jhelom (West Side)",
        "cost": 40,
        "train": 2,
        "combat": 2,
        "dexterity": 0,
        "intelligence": 0,
        "magic": 0,
        "strength": 0
    },
    {
        "id": 4,
        "name": "Denby",
        "location": "Britain (above Apothecary's)",
        "cost": 75,
        "train": 3,
        "combat": 0,
        "dexterity": 1,
        "intelligence": 1,
        "magic": 1,
        "strength": 0
    },
    {
        "id": 5,
        "name": "Inforlem - warrior",
        "location": "Terfin",
        "cost": 50,
        "train": 3,
        "combat": 1,
        "dexterity": 1,
        "intelligence": 0,
        "magic": 0,
        "strength": 1
    },
    {
        "id": 6,
        "name": "Inforlem - mage",
        "location": "Terfin",
        "cost": 50,
        "train": 3,
        "combat": 0,
        "dexterity": 0,
        "intelligence": 2,
        "magic": 1,
        "strength": 0
    },
    {
        "id": 7,
        "name": "Jakher",
        "location": "Minoc (NE house)",
        "cost": 20,
        "train": 2,
        "combat": 0,
        "dexterity": 0,
        "intelligence": 1,
        "magic": 0,
        "strength": 1
    },
    {
        "id": 8,
        "name": "Jillian",
        "location": "Moonglow (Lycaeum)",
        "cost": 35,
        "train": 2,
        "combat": 0,
        "dexterity": 0,
        "intelligence": 1,
        "magic": 1,
        "strength": 0
    },
    {
        "id": 9,
        "name": "Karenna",
        "location": "Minoc (NE house)",
        "cost": 20,
        "train": 3,
        "combat": 1,
        "dexterity": 2,
        "intelligence": 0,
        "magic": 0,
        "strength": 0
    },
    {
        "id": 10,
        "name": "Lucky",
        "location": "Buccaneer's Den",
        "cost": 35,
        "train": 1,
        "combat": 0,
        "dexterity": 0,
        "intelligence": 1,
        "magic": 0,
        "strength": 0
    },
    {
        "id": 11,
        "name": "Markus",
        "location": "Trinsic",
        "cost": 20,
        "train": 1,
        "combat": 1,
        "dexterity": 0,
        "intelligence": 0,
        "magic": 0,
        "strength": 0
    },
    {
        "id": 12,
        "name": "Menion",
        "location": "Serpent's Hold",
        "cost": 45,
        "train": 3,
        "combat": 1,
        "dexterity": 0,
        "intelligence": 0,
        "magic": 0,
        "strength": 2
    },
    {
        "id": 13,
        "name": "Penni",
        "location": "Yew (Outer area)",
        "cost": 35,
        "train": 2,
        "combat": 1,
        "dexterity": 0,
        "intelligence": 0,
        "magic": 0,
        "strength": 1
    },
    {
        "id": 14,
        "name": "Perrin",
        "location": "Yew (near Abbey)",
        "cost": 45,
        "train": 3,
        "combat": 0,
        "dexterity": 0,
        "intelligence": 2,
        "magic": 1,
        "strength": 0
    },
    {
        "id": 15,
        "name": "Rayburt",
        "location": "Cove",
        "cost": 60,
        "train": 3,
        "combat": 1,
        "dexterity": 1,
        "intelligence": 1,
        "magic": 0,
        "strength": 0
    },
    {
        "id": 16,
        "name": "Sentri",
        "location": "Britain (East Side)",
        "cost": 30,
        "train": 1,
        "combat": 0,
        "dexterity": 1,
        "intelligence": 0,
        "magic": 0,
        "strength": 0
    },
    {
        "id": 17,
        "name": "Zaksam",
        "location": "Vesper",
        "cost": 40,
        "train": 3,
        "combat": 2,
        "dexterity": 0,
        "intelligence": 0,
        "magic": 0,
        "strength": 1
    },
    {
        "id": 18,
        "name": "Zella",
        "location": "Britain (East Side)",
        "cost": 45,
        "train": 2,
        "combat": 1,
        "dexterity": 1,
        "intelligence": 0,
        "magic": 0,
        "strength": 0
    }
]

trainers = new Trainers();
trainers.add(trainerData);