var trainerData = [
    {
        "id": 1,
        "name": "Bradman",
        "location": "Yew (Outer area)",
        "x": 568,
        "y": 743,
        "cost": 30,
        "train": 2,
        "combat": 0,
        "dexterity": 2,
        "intelligence": 0,
        "magic": 0,
        "strength": 0
    },
    {
        "id": 2,
        "name": "Chad",
        "location": "Moonglow (far South)",
        "x": 2736,
        "y": 1839,
        "cost": 45,
        "train": 3,
        "combat": 1,
        "dexterity": 2,
        "intelligence": 0,
        "magic": 0,
        "strength": 0
    },
    {
        "id": 3,
        "name": "De Snel",
        "location": "Jhelom (West Side)",
        "x": 463,
        "y": 2511,
        "cost": 40,
        "train": 2,
        "combat": 2,
        "dexterity": 0,
        "intelligence": 0,
        "magic": 0,
        "strength": 0
    },
    {
        "id": 4,
        "name": "Denby",
        "location": "Britain (above Apothecary's)",
        "x": 839,
        "y": 1415,
        "cost": 75,
        "train": 3,
        "combat": 0,
        "dexterity": 1,
        "intelligence": 1,
        "magic": 1,
        "strength": 0
    },
    {
        "id": 5,
        "name": "Inforlem - warrior",
        "location": "Terfin",
        "x": 2102,
        "y": 2896,
        "cost": 50,
        "train": 3,
        "combat": 1,
        "dexterity": 1,
        "intelligence": 0,
        "magic": 0,
        "strength": 1
    },
    {
        "id": 6,
        "name": "Inforlem - mage",
        "location": "Terfin",
        "x": 2102,
        "y": 2896,
        "cost": 50,
        "train": 3,
        "combat": 0,
        "dexterity": 0,
        "intelligence": 2,
        "magic": 1,
        "strength": 0
    },
    {
        "id": 7,
        "name": "Jakher",
        "location": "Minoc (NE house)",
        "x": 1630,
        "y": 294,
        "cost": 20,
        "train": 2,
        "combat": 0,
        "dexterity": 0,
        "intelligence": 1,
        "magic": 0,
        "strength": 1
    },
    {
        "id": 8,
        "name": "Jillian",
        "location": "Moonglow (Lycaeum)",
        "x": 2681,
        "y": 1569,
        "cost": 35,
        "train": 2,
        "combat": 0,
        "dexterity": 0,
        "intelligence": 1,
        "magic": 1,
        "strength": 0
    },
    {
        "id": 9,
        "name": "Karenna",
        "location": "Minoc (NE house)",
        "x": 1630,
        "y": 294,
        "cost": 20,
        "train": 3,
        "combat": 1,
        "dexterity": 2,
        "intelligence": 0,
        "magic": 0,
        "strength": 0
    },
    {
        "id": 10,
        "name": "Lucky",
        "location": "Buccaneer's Den",
        "x": 1639,
        "y": 1948,
        "cost": 35,
        "train": 1,
        "combat": 0,
        "dexterity": 0,
        "intelligence": 1,
        "magic": 0,
        "strength": 0
    },
    {
        "id": 11,
        "name": "Markus",
        "location": "Trinsic",
        "x": 994,
        "y": 2151,
        "cost": 20,
        "train": 1,
        "combat": 1,
        "dexterity": 0,
        "intelligence": 0,
        "magic": 0,
        "strength": 0
    },
    {
        "id": 12,
        "name": "Menion",
        "location": "Serpent's Hold",
        "x": 1425,
        "y": 2839,
        "cost": 45,
        "train": 3,
        "combat": 1,
        "dexterity": 0,
        "intelligence": 0,
        "magic": 0,
        "strength": 2
    },
    {
        "id": 13,
        "name": "Penni",
        "location": "Yew (Outer area)",
        "x": 551,
        "y": 663,
        "cost": 35,
        "train": 2,
        "combat": 1,
        "dexterity": 0,
        "intelligence": 0,
        "magic": 0,
        "strength": 1
    },
    {
        "id": 14,
        "name": "Perrin",
        "location": "Yew (near Abbey)",
        "x": 248,
        "y": 311,
        "cost": 45,
        "train": 3,
        "combat": 0,
        "dexterity": 0,
        "intelligence": 2,
        "magic": 1,
        "strength": 0
    },
    {
        "id": 15,
        "name": "Rayburt",
        "location": "Cove",
        "x": 1576,
        "y": 1241,
        "cost": 60,
        "train": 3,
        "combat": 1,
        "dexterity": 1,
        "intelligence": 1,
        "magic": 0,
        "strength": 0
    },
    {
        "id": 16,
        "name": "Sentri",
        "location": "Britain (East Side)",
        "x": 759,
        "y": 1376,
        "cost": 30,
        "train": 1,
        "combat": 0,
        "dexterity": 1,
        "intelligence": 0,
        "magic": 0,
        "strength": 0
    },
    {
        "id": 17,
        "name": "Zaksam",
        "location": "Vesper",
        "x": 2200,
        "y": 1191,
        "cost": 40,
        "train": 3,
        "combat": 2,
        "dexterity": 0,
        "intelligence": 0,
        "magic": 0,
        "strength": 1
    },
    {
        "id": 18,
        "name": "Zella",
        "location": "Britain (East Side)",
        "x": 752,
        "y": 1328,
        "cost": 45,
        "train": 2,
        "combat": 1,
        "dexterity": 1,
        "intelligence": 0,
        "magic": 0,
        "strength": 0
    }
]

var trainers = new Trainers();
var trainersSelected = new TrainersSelected();
trainers.add(trainerData);
